# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
defaults: &defaults
  working_directory: ~/react-boilerplate
  docker:
    - image: circleci/node:7.10

version: 2
jobs:
  checkout-code-and-build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - react-boilerplate-yarn-{{ checksum "package.json" }}
            - react-boilerplate-yarn
            - react-boilerplate-
      - run: yarn install
      - save_cache:
          key: react-boilerplate-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/react-boilerplate
      - save_cache:
          key: react-boilerplate-yarn-{{ checksum "package.json" }}
          paths:
            - node_modules

  test:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - react-boilerplate-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Jest Suite
          command: yarn run test --ci --testResultsProcessor="jest-junit" --runInBand
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  test-build:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - react-boilerplate-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Build release
          command: yarn run build --release


  deploy-job:
      <<: *defaults
      steps:
        - add_ssh_keys:
            fingerprints:
              - "6a:98:74:ef:a1:1c:97:14:e8:da:d2:6f:d2:27:be:e4"
        - restore_cache:
            keys:
              - react-boilerplate-{{ .Environment.CIRCLE_SHA1 }}
        - run:
            name: Run Setup
            command: |
              wget https://cli-assets.heroku.com/branches/stable/heroku-linux-amd64.tar.gz
              sudo mkdir -p /usr/local/lib /usr/local/bin
              sudo tar -xvzf heroku-linux-amd64.tar.gz -C /usr/local/lib
              sudo ln -s /usr/local/lib/heroku/bin/heroku /usr/local/bin/heroku
        - run:
            name: Update Config
            command: |
              cat > ~/.netrc << EOF
              machine api.heroku.com
                login $HEROKU_LOGIN
                password $HEROKU_API_KEY

              machine git.heroku.com
                login $HEROKU_LOGIN
                password $HEROKU_API_KEY
              EOF
              cat >> ~/.ssh/config << EOF

              Host *
                 VerifyHostKeyDNS yes
                 StrictHostKeyChecking no
              EOF
              git config --global user.email "jvburen@thoughtworks.com"
              git config --global user.name "Jonathan Van Buren"
              heroku git:remote -a $HEROKU_APP
        - run:
           name: Deploy Master to Heroku
           command: yarn run deploy

workflows:
   version: 2
   build-and-deploy:
      jobs:
        - checkout-code-and-build
        - test:
            requires:
              - checkout-code-and-build
        - test-build:
            requires:
              - checkout-code-and-build
        - deploy-job:
            requires:
              - test
              - test-build
